<?php

// This file was generated by running "composer dump-env prod"

/*
return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '31a1418af67166bce55a5a1cf6a78539',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/bilemo',
  'PICTURE_SRC' => '/img/productsImg/',
  'MAILER_USER' => 'michael.garret.france@gmail.com',
  'MAILER_URL' => 'null://localhost',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '2c921b8c3a0218fbe7b7efe7d0e70c97',
  'REDIS_URL' => 'redis://localhost',
);*/


return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '31a1418af67166bce55a5a1cf6a78539',
  'DATABASE_URL' => 'mysql://dbu398238:.Mlgt.180391@db5000361097.hosting-data.io:3306/dbs350433',
  'PICTURE_SRC' => '/img/productsImg/',
  'MAILER_USER' => 'michael.garret.france@gmail.com',
  'MAILER_URL' => 'null://localhost',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '2c921b8c3a0218fbe7b7efe7d0e70c97',
  'REDIS_URL' => 'redis://localhost',
);