security:

    encoders:
        App\Entity\Client:
            algorithm: argon2i

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Client
                property: email

    firewalls:

        main:
            pattern: ^/login
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

        api_doc:
            pattern: ^/api/doc
            security: false

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                     - lexik_jwt_authentication.jwt_token_authenticator


    access_control:
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }



