sensio_framework_extra:
    router:
        annotations: false
    view: { annotations: true }
    request: { converters: true }

fos_http_cache:
    cache_control:
        defaults:
            overwrite: true
        rules:
            -
                match:
                    path: ^/api/product
                headers:
                    cache_control:
                        public: true
                        s_maxage: 3600
                        max_age : 3600
                    etag : "strong"
            -
                match:
                    path: ^/api/products
                headers:
                    cache_control:
                        public: true
                        s_maxage: 1800
                        max_age: 1800
                    etag: "strong"
            -
                match:
                    path: ^/api/user
                headers:
                    cache_control:
                        public: true
                        s_maxage: 3600
                        max_age: 3600
                    etag: "strong"
            -
                match:
                    path: ^/api/users
                    headers:
                        cache_control:
                            public: true
                            s_maxage: 1800
                            max_age: 1800
                        etag: "strong"
